sudo: false
language: python
python: 2.7
branches:  # remove travis double-check on pull requests in main repo
  only:
    - master
    - /^\d\.\d+$/
env:
  - TOXENV=py26
  - TOXENV=py27
  - TOXENV=pypy
before_install:
  - pip install codecov
install:
  - pip install 'coverage<4'
  - pip install tox coveralls
script:
  - tox
after_success:
  - coveralls
  - codecov
